// Static map of file extensions to Monaco language IDs.
const staticMap: Record<string, string> = {
	js: 'javascript',
	es6: 'javascript',
	jsx: 'javascript',
	cjs: 'javascript',
	mjs: 'javascript',
	ts: 'typescript',
	tsx: 'typescript',
	cts: 'typescript',
	mts: 'typescript',
	json: 'json',
	jsonc: 'json',
	py: 'python',
	gyp: 'python',
	gypi: 'python',
	css: 'css',
	scss: 'scss',
	less: 'less',
	html: 'html',
	htm: 'html',
	xhtml: 'html',
	jsp: 'html',
	asp: 'html',
	aspx: 'html',
	vue: 'html',
	svelte: 'html',
	astro: 'html',
	cpp: 'cpp',
	cc: 'cpp',
	cxx: 'cpp',
	hpp: 'cpp',
	hh: 'cpp',
	hxx: 'cpp',
	c: 'c',
	h: 'c',
	cs: 'csharp',
	csx: 'csharp',
	java: 'java',
	go: 'go',
	rs: 'rust',
	rb: 'ruby',
	gemspec: 'ruby',
	php: 'php',
	phtml: 'php',
	swift: 'swift',
	kt: 'kotlin',
	kts: 'kotlin',
	sql: 'sql',
	yaml: 'yaml',
	yml: 'yaml',
	lock: 'yaml',
	xml: 'xml',
	xsd: 'xml',
	dtd: 'xml',
	xaml: 'xml',
	xsl: 'xml',
	xslt: 'xml',
	md: 'markdown',
	mdx: 'markdown',
	markdown: 'markdown',
	mmd: 'mermaid',
	mermaid: 'mermaid',
	sh: 'shell',
	bash: 'shell',
	fish: 'shell',
	zsh: 'shell',
	csh: 'shell',
	ps1: 'powershell',
	psm1: 'powershell',
	psd1: 'powershell',
	bat: 'bat',
	cmd: 'bat',
	lua: 'lua',
	r: 'r',
	dart: 'dart',
	scala: 'scala',
	sc: 'scala',
	jl: 'julia',
	tf: 'hcl',
	hcl: 'hcl',
	tfvars: 'hcl',
	ini: 'ini',
	properties: 'ini',
	nginx: 'ini',
	env: 'ini',
	toml: 'toml',
	dockerfile: 'dockerfile',
	graphql: 'graphql',
	gql: 'graphql',
	hbs: 'handlebars',
	groovy: 'groovy',
	gradle: 'groovy',
	pas: 'pascal',
	pp: 'pascal',
	vb: 'vb',
	pl: 'perl',
	pm: 'perl',
	ex: 'elixir',
	exs: 'elixir',
	pug: 'pug',
	jade: 'pug',
	rst: 'restructuredtext',
	proto: 'proto',
	sol: 'sol',
	wasm: 'wat',
	asm: 'asm',
	prisma: 'prisma'
};

/** Returns the Monaco language id for a given file extension. */
export function getLanguage(extension: string): string {
	return staticMap[extension] ?? 'plaintext';
}

/** Returns all known code extensions, minus exclusions. */
export function getAllMonacoExtensions(excludedExtensions: string[]): string[] {
	const excluded = new Set(excludedExtensions);
	return Object.keys(staticMap).filter((ext) => !excluded.has(ext));
}
