import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { config } from 'dotenv';
import path from 'path';
import { readFileSync } from 'fs';
import { rm, cp, copyFile } from 'fs/promises';
import fs from 'fs';
import {
	isValidPath,
	copyFilesToTargetDir,
	createReadlineInterface,
	isInPluginsFolder,
	getVaultPath,
	updateEnvFile,
	ensureEnvFile,
	promptForVaultPath
} from './utils.js';

// Determine the plugin directory (where the script is called from)
const pluginDir = process.cwd();

// Create readline interface for prompts
const rl = createReadlineInterface();

const manifestPath = path.join(pluginDir, 'manifest.json');

// Check if manifest exists (for plugin-config itself, it might not exist)
if (!fs.existsSync(manifestPath)) {
	console.log(
		'⚠️  No manifest.json found - this script is designed for Obsidian plugins'
	);
	console.log("   If you're building plugin-config itself, use 'tsc' instead");
	process.exit(0);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));

config();

const EXTERNAL_DEPS = [
	'obsidian',
	'electron',
	'@codemirror/autocomplete',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	...builtins
];

const BANNER = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

/**
 * Check that the environment is valid
 * - main.ts exists in src/
 * - manifest.json exists and is valid JSON
 */
async function validateEnvironment(): Promise<void> {
	const srcMainPath = path.join(pluginDir, 'src/main.ts');
	if (!(await isValidPath(srcMainPath))) {
		throw new Error(
			'Invalid path for src/main.ts. main.ts must be in the src directory'
		);
	}
	if (!(await isValidPath(manifestPath))) {
		throw new Error('Invalid path for manifest.json');
	}
}

/**
 * Get the build path based on the environment and user input
 *
 * @Param _isProd Whether this is a production build (true for 'production' arg, false for 'watch'/'dev')
 * @return The path to build the plugin to (either the vault plugins folder or the initial folder for in-place development)
 */
async function getBuildPath(_isProd: boolean): Promise<string> {
	// In-place development: already inside a plugins folder
	if (isInPluginsFolder(pluginDir)) {
		console.log('ℹ️  Building in Obsidian plugins folder (in-place development)');
		return pluginDir;
	}

	// External development
	const useRealVault = process.argv.includes('-r') || process.argv.includes('real');
	const envKey = useRealVault ? 'REAL_VAULT' : 'TEST_VAULT';
	const envPath = path.join(pluginDir, '.env');

	await ensureEnvFile(envPath);
	config(); // reload after potential creation

	const vaultPath = process.env[envKey]?.trim();

	// Prompt if missing or still a placeholder
	if (!vaultPath || vaultPath.startsWith('/path/to/your/')) {
		const newPath = await promptForVaultPath(envKey, rl);
		await updateEnvFile(envKey, newPath, envPath);
		config();
		return getVaultPath(newPath, manifest.id);
	}

	return getVaultPath(vaultPath, manifest.id);
}

async function createBuildContext(
	buildPath: string,
	isProd: boolean,
	entryPoints: string[]
): Promise<esbuild.BuildContext> {
	const plugins = [
		{
			name: 'copy-to-plugins-folder',
			setup: (build: esbuild.PluginBuild): void => {
				build.onEnd(async () => {
					const monacoSrc = path.join(
						pluginDir,
						'node_modules/monaco-editor/min/vs'
					);
					const monacoTarget = path.join(buildPath, 'vs');
					const htmlSrc = path.join(pluginDir, 'src/editor/monacoEditor.html');
					const htmlTarget = path.join(buildPath, 'monacoEditor.html');
					const configJsSrc = path.join(pluginDir, 'src/editor/monacoHtml.js');
					const configJsTarget = path.join(buildPath, 'monacoHtml.js');
					const formattersJsSrc = path.join(pluginDir, 'src/editor/monacoFormatters.js');
					const formattersJsTarget = path.join(buildPath, 'monacoFormatters.js');
					const diffJsSrc = path.join(pluginDir, 'src/editor/monacoDiff.js');
					const diffJsTarget = path.join(buildPath, 'monacoDiff.js');
					const actionsJsSrc = path.join(pluginDir, 'src/editor/monacoActions.js');
					const actionsJsTarget = path.join(buildPath, 'monacoActions.js');
					const configCssSrc = path.join(
						pluginDir,
						'src/editor/monacoHtml.css'
					);
					const configCssTarget = path.join(buildPath, 'monacoHtml.css');
					const themesSrc = path.join(
						pluginDir,
						'node_modules/monaco-themes/themes'
					);
					const themesTarget = path.join(buildPath, 'monaco-themes');
					const formattersTarget = path.join(buildPath, 'formatters');
					await cp(monacoSrc, monacoTarget, { recursive: true });
					// Copy Codicons font so Monaco's @font-face can load it via app:// URL
					// (Obsidian's CSP blocks data: font sources in child iframes)
					const codiconSrc = path.join(
						pluginDir,
						'node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf'
					);
					const codiconTarget = path.join(buildPath, 'vs/editor/codicon.ttf');
					await copyFile(codiconSrc, codiconTarget);
					// Create formatters directory
					await fs.promises.mkdir(formattersTarget, { recursive: true });
					// Copy Prettier and Mermaid formatters to formatters/ folder
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/standalone.js'),
						path.join(formattersTarget, 'prettier-standalone.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/markdown.js'),
						path.join(formattersTarget, 'prettier-markdown.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/estree.js'),
						path.join(formattersTarget, 'prettier-estree.js')
					);
					await copyFile(
						path.join(
							pluginDir,
							'node_modules/prettier/plugins/typescript.js'
						),
						path.join(formattersTarget, 'prettier-typescript.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/babel.js'),
						path.join(formattersTarget, 'prettier-babel.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/postcss.js'),
						path.join(formattersTarget, 'prettier-postcss.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/html.js'),
						path.join(formattersTarget, 'prettier-html.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/yaml.js'),
						path.join(formattersTarget, 'prettier-yaml.js')
					);
					await copyFile(
						path.join(pluginDir, 'node_modules/prettier/plugins/graphql.js'),
						path.join(formattersTarget, 'prettier-graphql.js')
					);
					// Bundle mermaid-formatter for browser
					await esbuild.build({
						entryPoints: [
							path.join(pluginDir, 'src/mermaid-formatter-bundle-entry.js')
						],
						bundle: true,
						format: 'iife', // Wrap in (function(){...})() for <script> tag loading in the Monaco iframe
						outfile: path.join(formattersTarget, 'mermaid-formatter.js'),
						platform: 'browser',
						minify: isProd
					});
					// Bundle ruff-formatter (Python) for browser
					await esbuild.build({
						entryPoints: [
							path.join(pluginDir, 'src/ruff-formatter-bundle-entry.js')
						],
						bundle: true,
						format: 'iife',
						outfile: path.join(formattersTarget, 'ruff-formatter.js'),
						platform: 'browser',
						minify: isProd,
						loader: {
							'.wasm': 'file'
						},
						metafile: true
					});
					// Copy WASM file to formatters/ folder
					const wasmSrc = path.join(
						pluginDir,
						'node_modules/@wasm-fmt/ruff_fmt/ruff_fmt_bg.wasm'
					);
					const wasmTarget = path.join(formattersTarget, 'ruff_fmt_bg.wasm');
					await copyFile(wasmSrc, wasmTarget);
					// Bundle gofmt-formatter (Go) for browser
					await esbuild.build({
						entryPoints: [
							path.join(pluginDir, 'src/gofmt-formatter-bundle-entry.js')
						],
						bundle: true,
						format: 'iife',
						outfile: path.join(formattersTarget, 'gofmt-formatter.js'),
						platform: 'browser',
						minify: isProd,
						loader: {
							'.wasm': 'file'
						},
						metafile: true
					});
					// Copy WASM file to formatters/ folder
					const gofmtWasmSrc = path.join(
						pluginDir,
						'node_modules/@wasm-fmt/gofmt/gofmt.wasm'
					);
					const gofmtWasmTarget = path.join(formattersTarget, 'gofmt.wasm');
					await copyFile(gofmtWasmSrc, gofmtWasmTarget);
					// Bundle clang-format (C/C++) for browser
					await esbuild.build({
						entryPoints: [
							path.join(pluginDir, 'src/clang-format-bundle-entry.js')
						],
						bundle: true,
						format: 'iife',
						outfile: path.join(formattersTarget, 'clang-formatter.js'),
						platform: 'browser',
						minify: isProd,
						loader: {
							'.wasm': 'file'
						},
						metafile: true
					});
					// Copy WASM file to formatters/ folder
					const clangWasmSrc = path.join(
						pluginDir,
						'node_modules/@wasm-fmt/clang-format/clang-format.wasm'
					);
					const clangWasmTarget = path.join(
						formattersTarget,
						'clang-format.wasm'
					);
					await copyFile(clangWasmSrc, clangWasmTarget);
					await copyFile(htmlSrc, htmlTarget);
					await copyFile(configJsSrc, configJsTarget);
					await copyFile(formattersJsSrc, formattersJsTarget);
					await copyFile(diffJsSrc, diffJsTarget);
					await copyFile(actionsJsSrc, actionsJsTarget);
					await copyFile(configCssSrc, configCssTarget);
					await cp(themesSrc, themesTarget, { recursive: true });
					// if real or build
					if (isProd) {
						if (
							process.argv.includes('-r') ||
							process.argv.includes('real')
						) {
							await copyFilesToTargetDir(buildPath);
							console.log(`Successfully installed in ${buildPath}`);
						} else {
							const folderToRemove = path.join(buildPath, '_.._');
							if (await isValidPath(folderToRemove)) {
								await rm(folderToRemove, { recursive: true });
							}
							console.log('Build done in initial folder');
						}
					}
					// if watch (dev)
					else {
						await copyFilesToTargetDir(buildPath);
					}
				});
			}
		}
	];

	return await esbuild.context({
		banner: { js: BANNER },
		minify: isProd,
		entryPoints,
		bundle: true,
		external: EXTERNAL_DEPS,
		format: 'cjs',
		target: 'esNext',
		platform: 'node',
		logLevel: 'info',
		sourcemap: isProd ? false : 'inline',
		treeShaking: true,
		outdir: buildPath,
		outbase: path.join(pluginDir, 'src'),
		plugins
	});
}

async function main(): Promise<void> {
	try {
		await validateEnvironment();
		const isProd = process.argv[2] === 'production';
		const buildPath = await getBuildPath(isProd);
		console.log(
			buildPath === pluginDir
				? 'Building in initial folder'
				: `Building in ${buildPath}`
		);

		// Check for CSS in root
		const stylesPath = path.join(pluginDir, 'styles.css');
		const stylePath = (await isValidPath(stylesPath)) ? stylesPath : '';

		const mainTsPath = path.join(pluginDir, 'src/main.ts');
		const entryPoints = stylePath ? [mainTsPath, stylePath] : [mainTsPath];
		const context = await createBuildContext(buildPath, isProd, entryPoints);

		if (isProd) {
			await context.rebuild();
			rl.close();
			process.exit(0);
		} else {
			await context.watch();
		}
	} catch (error) {
		console.error('Build failed:', error);
		rl.close();
		process.exit(1);
	}
}

main().catch(console.error);
