import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { config } from 'dotenv';
import path from 'path';
import { readFileSync } from 'fs';
import { rm, mkdir } from 'fs/promises';
import fs from 'fs';
import { bundleFormatters } from './build/formatters.js';
import { copyMonacoAssets, copyEditorFiles } from './build/assets.js';
import { obsidianTypingsPlugin } from './build/typingsPlugin.js';
import {
	isValidPath,
	copyFilesToTargetDir,
	createReadlineInterface,
	isInPluginsFolder,
	getVaultPath,
	updateEnvFile,
	ensureEnvFile,
	promptForVaultPath
} from './utils.js';

// Determine the plugin directory (where the script is called from)
const pluginDir = process.cwd();

// Create readline interface for prompts
const rl = createReadlineInterface();

const manifestPath = path.join(pluginDir, 'manifest.json');

// Check if manifest exists (for plugin-config itself, it might not exist)
if (!fs.existsSync(manifestPath)) {
	console.log(
		'⚠️  No manifest.json found - this script is designed for Obsidian plugins'
	);
	console.log("   If you're building plugin-config itself, use 'tsc' instead");
	process.exit(0);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));

config();

const EXTERNAL_DEPS = [
	'obsidian',
	'electron',
	'@codemirror/autocomplete',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	...builtins
];

const BANNER = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

/**
 * Check that the environment is valid
 * - main.ts exists in src/
 * - manifest.json exists and is valid JSON
 */
async function validateEnvironment(): Promise<void> {
	const srcMainPath = path.join(pluginDir, 'src/main.ts');
	if (!(await isValidPath(srcMainPath))) {
		throw new Error(
			'Invalid path for src/main.ts. main.ts must be in the src directory'
		);
	}
	if (!(await isValidPath(manifestPath))) {
		throw new Error('Invalid path for manifest.json');
	}
}

/**
 * Get the build path based on the environment and user input
 *
 * @Param _isProd Whether this is a production build (true for 'production' arg, false for 'watch'/'dev')
 * @return The path to build the plugin to (either the vault plugins folder or the initial folder for in-place development)
 */
async function getBuildPath(_isProd: boolean): Promise<string> {
	// In-place development: already inside a plugins folder
	if (isInPluginsFolder(pluginDir)) {
		console.log('ℹ️  Building in Obsidian plugins folder (in-place development)');
		return pluginDir;
	}

	// External development
	const useRealVault = process.argv.includes('-r') || process.argv.includes('real');
	const envKey = useRealVault ? 'REAL_VAULT' : 'TEST_VAULT';
	const envPath = path.join(pluginDir, '.env');

	await ensureEnvFile(envPath);
	config(); // reload after potential creation

	const vaultPath = process.env[envKey]?.trim();

	// Prompt if missing or still a placeholder
	if (!vaultPath || vaultPath.startsWith('/path/to/your/')) {
		const newPath = await promptForVaultPath(envKey, rl);
		await updateEnvFile(envKey, newPath, envPath);
		config();
		return getVaultPath(newPath, manifest.id);
	}

	return getVaultPath(vaultPath, manifest.id);
}

async function createBuildContext(
	buildPath: string,
	isProd: boolean,
	entryPoints: string[]
): Promise<esbuild.BuildContext> {
	const plugins = [
		{
			name: 'copy-to-plugins-folder',
			setup: (build: esbuild.PluginBuild): void => {
				build.onEnd(async () => {
					const formattersTarget = path.join(buildPath, 'formatters');
					await mkdir(formattersTarget, { recursive: true });
					await copyMonacoAssets(pluginDir, buildPath);
					await copyEditorFiles(pluginDir, buildPath);
					await bundleFormatters(pluginDir, formattersTarget, isProd);

					if (isProd) {
						if (
							process.argv.includes('-r') ||
							process.argv.includes('real')
						) {
							await copyFilesToTargetDir(buildPath);
							console.log(`Successfully installed in ${buildPath}`);
						} else {
							const folderToRemove = path.join(buildPath, '_.._');
							if (await isValidPath(folderToRemove)) {
								await rm(folderToRemove, { recursive: true });
							}
							console.log('Build done in initial folder');
						}
					} else {
						await copyFilesToTargetDir(buildPath);
					}
				});
			}
		}
	];

	return await esbuild.context({
		banner: { js: BANNER },
		minify: isProd,
		entryPoints,
		bundle: true,
		external: EXTERNAL_DEPS,
		format: 'cjs',
		target: 'esNext',
		platform: 'node',
		logLevel: 'info',
		sourcemap: isProd ? false : 'inline',
		treeShaking: true,
		outdir: buildPath,
		outbase: path.join(pluginDir, 'src'),
		plugins: [obsidianTypingsPlugin(pluginDir), ...plugins]
	});
}

async function main(): Promise<void> {
	try {
		await validateEnvironment();
		const isProd = process.argv[2] === 'production';
		const buildPath = await getBuildPath(isProd);
		console.log(
			buildPath === pluginDir
				? 'Building in initial folder'
				: `Building in ${buildPath}`
		);

		// Check for CSS in root
		const stylesPath = path.join(pluginDir, 'styles.css');
		const stylePath = (await isValidPath(stylesPath)) ? stylesPath : '';

		const mainTsPath = path.join(pluginDir, 'src/main.ts');
		const entryPoints = stylePath ? [mainTsPath, stylePath] : [mainTsPath];
		const context = await createBuildContext(buildPath, isProd, entryPoints);

		if (isProd) {
			await context.rebuild();
			rl.close();
			process.exit(0);
		} else {
			await context.watch();
		}
	} catch (error) {
		console.error('Build failed:', error);
		rl.close();
		process.exit(1);
	}
}

main().catch(console.error);
