export const themes: string[] = [
	'Active4D',
	'All Hallows Eve',
	'Amy',
	'Birds of Paradise',
	'Blackboard',
	'Brilliance Black',
	'Brilliance Dull',
	'Chrome DevTools',
	'Clouds Midnight',
	'Clouds',
	'Cobalt',
	'Cobalt2',
	'Dawn',
	'Dracula',
	'Dreamweaver',
	'Eiffel',
	'Espresso Libre',
	'GitHub Dark',
	'GitHub Light',
	'GitHub',
	'IDLE',
	'Katzenmilch',
	'Kuroir Theme',
	'LAZY',
	'MagicWB (Amiga)',
	'Merbivore Soft',
	'Merbivore',
	'Monokai Bright',
	'Monokai',
	'Night Owl',
	'Nord',
	'Oceanic Next',
	'Pastels on Dark',
	'Slush and Poppies',
	'Solarized-dark',
	'Solarized-light',
	'SpaceCadet',
	'Sunburst',
	'Textmate (Mac Classic)',
	'Tomorrow-Night-Blue',
	'Tomorrow-Night-Bright',
	'Tomorrow-Night-Eighties',
	'Tomorrow-Night',
	'Tomorrow',
	'Twilight',
	'Upstream Sunburst',
	'Vibrant Ink',
	'Xcode_default',
	'Zenburnesque',
	'iPlastic',
	'idleFingers',
	'krTheme',
	'monoindustrial'
];
